version: '3.4'
services:
  healthchecksui:
    image: xabarilcoding/healthchecksui:latest
    ports:
      - "5000:80"
    environment:
      - HealthChecks-UI:EvaluationTimeInSeconds=10
      - HealthChecks-UI:MinimumSecondsBetweenFailureNotifications=60
      - HealthChecks-UI:HealthChecks:0:Name=httpBasic
      - HealthChecks-UI:HealthChecks:0:Uri=http://localhost:47920/health        
  seq:
    image: datalust/seq:latest
    ports:
      - "5341:5341"
      - "15341:80"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - /c/!/data.ignore/seq:/data
  mssql:
    image: cilerler/mssql-server-linux:2017
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
      - SSIS_PID=Developer
      - SA_PASSWORD=Pass@word
    volumes:
      - /c/!/data.ignore/mssql:/var/opt/mssql
  rabbitmq:
    image: rabbitmq:3.7.10-management-alpine
    command: bash -c "rabbitmq-plugins enable rabbitmq_shovel rabbitmq_shovel_management && rabbitmq-server"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - /c/!/data.ignore/rabbitmq:/var/lib/rabbitmq/mnesia
    environment:
      - RABBITMQ_ERLANG_COOKIE=unique-erlang-cookie
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
    hostname: rabbit-1
  redis:
    image: redis:5.0.3-alpine
    ports:
      - "6379:6379"
    volumes:
      - /c/!/data.ignore/redis:/data
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "16379:8081"
    depends_on:
      - redis
  grafana:
    image: grafana/grafana:6.2.5
    environment:
      - GF_INSTALL_PLUGINS=raintank-worldping-app,grafana-azure-data-explorer-datasource
    ports:
      - "3000:3000"
    volumes:
      - /c/!/data.ignore/grafana:/var/lib/grafana
  prometheus-server:
    image: prom/prometheus:v2.11.1
    ports:
      - "9090:9090"
  prometheus-pushgateway:
    image: prom/pushgateway:v0.8.0
    ports:
      - "9091:9091"      
  prometheus-alertmanager:
    image: prom/alertmanager:v0.18.0
    ports:
      - "9093:9093"
  prometheus-node-exporter:
    image: prom/node-exporter:v0.18.0
    ports:
      - "9100:9100"
  mongo:
    image: mongo:4.1.7
    ports:
      - "27017:27017"
  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    links:
      - mongo
  postgresql:
    image: postgres:11.1-alpine
    ports:
      - "5432:5432"
    volumes:
      - /c/!/data.ignore/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=Pass@word
  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@pgadmin.local
      - PGADMIN_DEFAULT_PASSWORD=Pass@word
    links:
      - postgresql  
